version: "3"
services:
  hub:
    image: selenium/hub:3.14
    ports:
      - "8082:4444"
  node01:
    image: selenium/node-chrome:3.14
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  node02:
    image: selenium/node-chrome:3.14
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub